name: dmc_normal
log_path: logs/dmc_normal
gpu_ids: 0
num_threads: 1
batch_size: 4

# path
load_netN_checkpoint_path: /media/data1/shaoruizhi/Multiview_Pair/checkpoints/retrain_fine_mask_att/netN_latest